name: 'macsplat-%Y-%m-%d-%H-%M-%S'
save_dir: './outputs/${name}/'

seed: 0
devices: [0]

use_profiler: false
loggers:
  use_csv_logger: true
  use_wandb: false

use_pretrained: true
pretrained_mast3r_path: 'checkpoints/macsplat.ckpt'

data:
  root: './scannetpp-main/'
  batch_size: 1
  num_workers: 8
  resolution: [512, 512]
  epochs_per_train_epoch: 20
  extrinsics_convention: c2w

opt:
  epochs: 10
  lr: 0.000001
  weight_decay: 0.1
  gradient_clip_val: 0.5

loss:
  mse_loss_weight: 1.0
  lpips_loss_weight: 0.1
  apply_mask: true
  average_over_mask: true

  novel_view_loss_weight: 0
  novel_view_warmup_steps: 2500
  fewview_nvc_t: 0.5
  fewview_alpha_thresh: 0.3
  fewview_agree_thresh_px: 1.5
  fewview_grad_thresh: 0.1
  fewview_shape_weight: 0.02
  fewview_opacity_weight: 0.02
  fewview_near: 0.01
  fewview_far: 1000.0

  match_subsample_stride: 8
  match_warmup_steps: 1000
  min_match_conf_start: 0.0
  min_match_conf_end: 0.5

  consistency_loss_weight: 0.2
  consistency_chunk_size: 1024

  consistency_pos_weight: 1.0
  consistency_shape_weight: 0.02
  consistency_opacity_weight: 0.1
  consistency_color_weight: 0.1

  mast3r_loss_weight: 0.0

use_offsets: true
sh_degree: 1

test_params:
  - {alpha: 0.9, beta: 0.9}
  - {alpha: 0.7, beta: 0.7}
  - {alpha: 0.5, beta: 0.5}
  - {alpha: 0.3, beta: 0.3}
